# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.synced_folder "./shared", "/media/shared"

  config.vm.provision "shell", inline: <<-SHELL
    export DEBIAN_FRONTEND=noninteractive
    apt-get update
    apt-get install -y lynis logcheck

    # VULS
    export GOPATH=/root/go
    apt-get install -y gcc make git
    git clone https://github.com/vulsio/vulsctl.git
    cd vulsctl/install-host/
    ./install.sh "-y"
    ./upgrade.sh

    # DATABASES
    ./oval.sh --ubuntu
    ./gost.sh --ubuntu &
    ./exploitdb.sh &
    ./msfdb.sh &
    ./kev.sh &
    ./cti.sh

    cd ..
    cp config.toml.localscan config.toml
    cp /media/shared/scan.sh .
    chown vagrant:vagrant -R /home/vagrant
  SHELL
end
